/*

Even Fibonacci numbers
   
Problem 2

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the even-valued terms.

*/

using System;
using System.Linq;
using System.Collections.Generic;

class Problem002
{
    public void Run()
    {
        // int limit = 4000000;
        int limit = 4000000;
        // MakeFibo(limit);
        var fiboList = CreateFiboList(limit);

        foreach (var item in fiboList)
        {
            Console.Write(item + " ");
            
        }
    }

    public static List<int> CreateFiboList(int limit)
    {
        int a = 1;
        int b = 2;
        int tmp = 0;
        List<int> fiboList = new List<int>(){1, 2};

        try
        {
            while(b < limit)
            {
                tmp = a;
                a = b;
                b = tmp + b;
                fiboList.Add(b);
            }
            
        }
        catch (System.Exception)
        {
            throw;
        }

        Console.WriteLine("fibo-list length: {0}. ", fiboList.Count );
        return fiboList;
    }
    public static void MakeFibo(int limit)
    {
        int a = 0;
        int b = 1;
        int sum = 0;
        int tmp = 0;

        try
        {
            while(b < limit)
            {
                tmp = a;
                a = b;
                b = tmp + b;

                if(b % 2 == 0)
                {
                    sum += b;
                    // Console.WriteLine("a: {0}, b: {1}, sum: {2}", a, b, sum);
                }
            }
        }
        catch (System.Exception)
        {
            throw;
        }

        Console.WriteLine("Loops: {0}. Sume: {1}", limit, sum);
    }

}